# Generated by Django 5.2.3 on 2025-11-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('language', models.CharField(max_length=10)),
            ],
        ),
    ]
