# Generated by Django 5.2.3 on 2025-11-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_path', models.CharField(max_length=50, null=True)),
                ('tmdb_id', models.CharField(max_length=25, null=True)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(null=True)),
                ('vote_average', models.FloatField(blank=True)),
                ('language', models.CharField(max_length=10)),
            ],
        ),
    ]
