# Generated by Django 5.2.3 on 2025-11-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_alter_movie_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(null=True),
        ),
    ]
