# Generated by Django 5.2.3 on 2025-11-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_alter_movie_release_year_alter_movie_vote_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(null=True),
        ),
    ]
