# Generated by Django 5.2.3 on 2025-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_alter_movie_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
