# Generated by Django 5.2.3 on 2025-11-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_movie_tmdb_id_alter_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
